### ISSUE TITLE
Terms & Conditions for using the labels

### ISSUE THREAD

**Issue by patel-zeel** [microsoft/satellite-imagery-labeling-tool#25]
Hello,

I had a question related to the Terms & Conditions related to the usage of labels generated from the [labeling tool](https://microsoft.github.io/satellite-imagery-labeling-tool/src/labeler.html). I saw that this project is licensed under the MIT license. However, I have some specific questions:

* In my understanding, the `Azure Maps Satellite` and other imagery layers on which the [labeling tool](https://microsoft.github.io/satellite-imagery-labeling-tool/src/labeler.html) works are proprietary. Are we allowed to use the [labeling tool](https://microsoft.github.io/satellite-imagery-labeling-tool/src/labeler.html) with `Azure Maps Satellite` imagery and other imagery layers to generate a massive number of annotations (a state scale or a country scale) for:
    1. a non-commercial research project.
    2. a "Section 8" non-profit organization (NPO) as per Indian government rules.
    3. a commercial use case.

If the answer to any of these is No, we'd like to know what is allowed under the ToS of this project.

**Comment by rbrundritt** [comment]
For the Azure Maps satellite imagery, there is no restrictions around tracing objects to create a data set. So you are fine with the Azure Maps Satellite imagery. As for the other satellite imagery types, each would have their own terms that you should verify. I believe the USGS imagery for example is considered open data, and the only requirement is if you are showing the original imagery, you have to show attribute information, but I'm not aware of any restrictions on drawing and extracting objects from the imagery (it's often used for machine learning scenarios and object detection scenarios).

Using the road map data would be an issue since that would already be a vector data set from TomTom, or Open Street Maps, and would require aligning with their terms.

**Comment by patel-zeel** [comment]
Thank you @rbrundritt! Your response is very helpful for us. I am closing this issue as my doubt is resolved by your answer.

**Comment by rbrundritt** [comment]
Note, you should be using your own Azure Maps account to access the imagery if you plan when running you training. We provide limited free access to Azure Maps imagery in the labelling tool to assist those who need to quickly create a set of labelled data (e.g. disaster response). If we find people abuse this, we will simply remove that free access. 

Note that there are many ways to get access to imagery for free:

- The Microsoft for Non Profit](https://www.microsoft.com/en-us/nonprofits/azure) provides free Azure credits to those who qualify.
- The [Microsoft for Startups program](https://www.microsoft.com/en-us/startups) provides up to $100K in Azure Credits.
- Other than the Azure Maps imagery, all the other imagery sets in this project are freely available. Note that the imagery in Azure Maps is the same imagery used by the [Bing Maps site](https://bing.com/maps)

**Comment by patel-zeel** [comment]
Sure thing, @rbrundritt. I appreciate your and your team's effort in making it available to the general public. I can assure you that None of our team members, including myself, are scrapping the imagery via this portal or from any other medium. We will go through the right channel to access the imagery :)

> Note that there are many ways to get access to imagery for free:

These are very helpful pointers. I will check them out.

**Comment by rbrundritt** [comment]
All good. Just realized that others may come across this thread and get ideas.
